.PHONY: clean All

All:
	@echo "----------Building project:[ move - Release ]----------"
	@"$(MAKE)" -f  "move.mk"
clean:
	@echo "----------Cleaning project:[ move - Release ]----------"
	@"$(MAKE)" -f  "move.mk" clean
